### PR TITLE
Use /2/sendouts and /2/send instead of the deprecated endpoints

### PR DESCRIPTION
**Pull request by soderwall**
Summary:
--------
There are two new endpoints /2/sendout and /2/send that
should be used instead of /2/batches and /2/sms since
these have been deprecated by Beepsend.

Intended effect:
--------
The new endpoints is now used for sending messages.

### CODE REVIEW

**Comment by Cromigon** [comment]
There's unhandled exception upon invalid request in Request.php
I tried to send an message trough $client->message->send() and got the following stacktrace:

PHP Notice:  Undefined index: errors in /path/to/beepsend-php/src/Beepsend/Request.php on line 181

Notice: Undefined index: errors in /path/to/beepsend-php/src/Beepsend/Request.php on line 181
PHP Fatal error:  Uncaught exception 'Beepsend\Exception\InvalidRequest' in /path/to/beepsend-php/src/Beepsend/Request.php:159
Stack trace:
#0 /path/to/beepsend-php/src/Beepsend/Request.php(74): Beepsend\Request->response(Array, '[{"description"...')
#1 /path/to/beepsend-php/src/Beepsend/Resource/Message.php(68): Beepsend\Request->execute('/send/', 'POST', Array)
#2 /path/to/beepsend-php/testshit.php(10): Beepsend\Resource\Message->send(0123456789, 'Inigo Montoya', 'My name is Inig...')
#3 {main}
  thrown in /path/to/beepsend-php/src/Beepsend/Request.php on line 159

Fatal error: Uncaught exception 'Beepsend\Exception\InvalidRequest' in /path/to/beepsend-php/src/Beepsend/Request.php:159
Stack trace:
#0 /path/to/beepsend-php/src/Beepsend/Request.php(74): Beepsend\Request->response(Array, '[{"description"...')
#1 /path/to/beepsend-php/src/Beepsend/Resource/Message.php(68): Beepsend\Request->execute('/send/', 'POST', Array)
#2 /path/to/beepsend-php/testshit.php(10): Beepsend\Resource\Message->send(0123456789, 'Inigo Montoya', 'My name is Inig...')
#3 {main}
  thrown in /path/to/beepsend-php/src/Beepsend/Request.php on line 159

**Comment by Cromigon** [comment]
Looks like a parse-error in the response-class.
When we get an 403 back, we look for errors.
But the object returned might not contain errors. 

Example:

array(2) {
["info"]=>
 array(26) {
  .
  .
  .
  }
  ["response"]=>
  string(65) "[{"description":"\"from\" can not be longer than 11 characters"}]"
}

**Comment by soderwall** [comment]
Good catch @Cromigon We not support the correct response structure.

**Comment by Cromigon** [comment]
Looking good my friend! :+1:

**Pull request merged**
